USE [master]
GO

/****** Object:  Database [TestAddUser]    Script Date: 20/03/2019 19:04:57 ******/
CREATE DATABASE [TestAddUser]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestAddUser', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TestAddUser.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestAddUser_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TestAddUser_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TestAddUser] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestAddUser].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestAddUser] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestAddUser] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestAddUser] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestAddUser] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestAddUser] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestAddUser] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestAddUser] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestAddUser] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestAddUser] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestAddUser] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestAddUser] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestAddUser] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestAddUser] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestAddUser] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestAddUser] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestAddUser] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestAddUser] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestAddUser] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestAddUser] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestAddUser] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestAddUser] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestAddUser] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestAddUser] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TestAddUser] SET  MULTI_USER 
GO

ALTER DATABASE [TestAddUser] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestAddUser] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestAddUser] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestAddUser] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TestAddUser] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestAddUser] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TestAddUser] SET  READ_WRITE 
GO


